### ISSUE TITLE
The checks are for unicorn, not twilio

### ISSUE THREAD

**Issue by okushchenko** [sensu-plugins/sensu-plugins-unicorn#1]
This repo must contain checks for unicorn: [two checks from here](https://github.com/sensu/sensu-community-plugins/tree/master/plugins/unicorn) and not [random check for twilio](https://github.com/sensu-plugins/sensu-plugins-unicorn/blob/master/bin/check-num-recordings.rb).

**Comment by thapakazi** [comment]
@alexgear yep... @mattyjones can you push your latest changes...
![unhappy_cat](https://cloud.githubusercontent.com/assets/1695906/9129669/68b8445e-3cfa-11e5-9ab9-796eba1608ce.gif)

**Comment by mattyjones** [comment]
@alexgear @zerOnepal 

all set
